FROM ruby:2.5.6

ENV BUNDLE_SILENCE_ROOT_WARNING=1

RUN  apt-get update 
RUN  apt-get -y install tar curl make gcc libssl-dev time libxml2-dev libxslt-dev

RUN which ruby
RUN ruby --version

COPY Gemfile .

RUN free -h

RUN env time bundle install
