FROM ubuntu:18.04

ENV LANG=en_US.UTF-8  
ENV BUNDLE_SILENCE_ROOT_WARNING=1

RUN  apt-get update 
RUN  apt-get -y install tar curl make gcc libssl-dev time libxml2-dev libxslt-dev

#RUN curl -L https://github.com/ruby/truffleruby-dev-builder/releases/download/builds-20200217-190341/truffleruby-head-ubuntu-18.04.tar.gz | tar xz
RUN curl -L https://github.com/ruby/truffleruby-dev-builder/releases/latest/download/truffleruby-head-ubuntu-18.04.tar.gz | tar xz
ENV PATH="/truffleruby-head/lib/llvm-toolchain/bin:/truffleruby-head/bin:$PATH"
RUN "/truffleruby-head/lib/truffle/post_install_hook.sh"
RUN which ruby
RUN ruby --version

COPY Gemfile  /

RUN free -h
RUN ruby --vm.XX:+PrintGCSummary -e0
RUN ruby --vm.XX:+PrintGCSummary -S bundle --version

RUN apt-get install -y locales
RUN locale-gen en_US.UTF-8

RUN env time bundle install
#RUN env time ruby --experimental-options --engine.Inlining=false --vm.Xmn256m --vm.Xmx3g  --vm.XX:+PrintGCSummary -S bundle install  
