name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install python modules
      run: pip install requests
    - name: Build the GraalVM Docker image
      run: docker build . --file Dockerfile-graalvm --build-arg BUILD_ID=$(python get_latest.py 20.1.0-dev)--tag graalvm:latest
    - name: Build the Rails Docker image
      run: docker build . --file Dockerfile-rails --tag rails:latest
