name: Docker Image CI

env:
  GRAAL_VERSION: 20.1.0-dev

on:
  push:
    branches:    
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '46 3 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby-head
    - run: ruby -v
    - name: Build the Rails Docker image
      run: docker build . --file Dockerfile-rails-truffleruby --tag rails-truffleruby:latest
    - name: Build the Rails Docker image
      run: docker build . --file Dockerfile-rails-mri --tag rails-mri:latest
