name: Number to Currenncy test

on:
  push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby-head
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: gem install actionview -v 5.2.4.1
    - run: ruby -e "require 'action_view'; puts ActionView::Helpers.number_to_currency(123.45)"
