name: Smoke test rails server

on:
  push

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo apt-get update
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: bundle version
    - run: gem install rails
    - run: which rails
    - run: rails -v
    - run: rails new blog
    - run: rails server &
      working-directory: ./blog
    - run: sleep 10
    - run: ls -l log  
      working-directory: ./blog   
    - name: wait until server starts
      run: |
        WAIT_COUNT=0 
        until cat log/development.log | grep -m 1 "Listening" || [ $WAIT_COUNT -eq 48 ]; do 
          echo "WAIT COUNT $(( WAIT_COUNT++ ))"
          sleep 5 
        done
      working-directory: ./blog
    - name: make a request each minute for 10 minutes
      run: |
        set -B # enable brace expansion
        for i in {1..10}; do
          curl http://localhost:3000
          sleep 60
        done
    - run: kill -ARLM $(cat tmp/pids/server.pid)
