name: Smoke test rails server

on:
  push

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.6, truffleruby, truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: sudo apt-get update
    - run: sudo apt-get install libsqlite3-dev libxml2-dev libxslt-dev
    - run: gem install rails
    - run: rails new blog
    - run: cd blog
    - run: rails server -d
    - run: |
        set -B # enable brace expansion
        for i in {1..10}; do
          curl http://localhost:3000
          sleep 60
        done
    - run: kill -ARLM $(cat tmp/pids/server.pid)
